# coding: utf-8

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

import unittest

import os
from pprint import pprint
from 2c2p_python_sdk import TwoCTwoP

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        twoctwop = TwoCTwoP(
        )
        self.assertIsNotNone(twoctwop)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
