# coding: utf-8

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class IppPlan(BaseModel):
    sequence_no: typing.Optional[int] = Field(None, alias='sequenceNo')

    period: typing.Optional[int] = Field(None, alias='period')

    interest_type: typing.Optional[typing.Optional[str]] = Field(None, alias='interestType')

    interest_rate: typing.Optional[typing.Union[int, float]] = Field(None, alias='interestRate')

    monthly_amount: typing.Optional[typing.Union[int, float]] = Field(None, alias='monthlyAmount')

    monthly_interest: typing.Optional[typing.Union[int, float]] = Field(None, alias='monthlyInterest')

    currency_code: typing.Optional[typing.Optional[str]] = Field(None, alias='currencyCode')

    label: typing.Optional[typing.Optional[str]] = Field(None, alias='label')

    terms: typing.Optional[typing.Optional[str]] = Field(None, alias='terms')

    pay_later_period: typing.Optional[typing.Optional[int]] = Field(None, alias='payLaterPeriod')
    class Config:
        arbitrary_types_allowed = True
