# coding: utf-8

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class MerchantDetails(BaseModel):
    id: typing.Optional[typing.Optional[str]] = Field(None, alias='id')

    name: typing.Optional[typing.Optional[str]] = Field(None, alias='name')

    address: typing.Optional[typing.Optional[str]] = Field(None, alias='address')

    email: typing.Optional[typing.Optional[str]] = Field(None, alias='email')

    logo_url: typing.Optional[typing.Optional[str]] = Field(None, alias='logoUrl')

    banner_url: typing.Optional[typing.Optional[str]] = Field(None, alias='bannerUrl')
    class Config:
        arbitrary_types_allowed = True
