# coding: utf-8

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from 2c2p_python_sdk.pydantic.merchant_configuration_payment_fx_rate import MerchantConfigurationPaymentFxRate

class MerchantConfigurationPaymentFx(BaseModel):
    mcp: typing.Optional[MerchantConfigurationPaymentFxRate] = Field(None, alias='mcp')

    dcc: typing.Optional[MerchantConfigurationPaymentFxRate] = Field(None, alias='dcc')

    apm_mcc: typing.Optional[MerchantConfigurationPaymentFxRate] = Field(None, alias='apmMcc')
    class Config:
        arbitrary_types_allowed = True
