# coding: utf-8

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from 2c2p_python_sdk.pydantic.payment_channel_preference import PaymentChannelPreference
from 2c2p_python_sdk.pydantic.user_preference import UserPreference

class PaymentUserPreference(BaseModel):
    preference: typing.Optional[UserPreference] = Field(None, alias='preference')

    payment_channels: typing.Optional[typing.Optional[typing.List[PaymentChannelPreference]]] = Field(None, alias='paymentChannels')
    class Config:
        arbitrary_types_allowed = True
