# coding: utf-8

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from 2c2p_python_sdk.pydantic.ipp_plan import IppPlan
from 2c2p_python_sdk.pydantic.payment_option_details_custom_data import PaymentOptionDetailsCustomData
from 2c2p_python_sdk.pydantic.payment_option_details_info_provider import PaymentOptionDetailsInfoProvider

class PaymentOptionDetailsInfo(BaseModel):
    terms: typing.Optional[typing.Optional[str]] = Field(None, alias='terms')

    promo_url: typing.Optional[typing.Optional[str]] = Field(None, alias='promoUrl')

    plans: typing.Optional[typing.Optional[typing.List[IppPlan]]] = Field(None, alias='plans')

    custom_data: typing.Optional[typing.Optional[typing.List[PaymentOptionDetailsCustomData]]] = Field(None, alias='customData')

    provider: typing.Optional[PaymentOptionDetailsInfoProvider] = Field(None, alias='provider')

    learn_more_url: typing.Optional[typing.Optional[str]] = Field(None, alias='learnMoreUrl')

    terms_consent: typing.Optional[bool] = Field(None, alias='termsConsent')
    class Config:
        arbitrary_types_allowed = True
