# coding: utf-8

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from 2c2p_python_sdk.pydantic.browser_details import BrowserDetails

class PaymentLoyaltyPointInfoRequest(BaseModel):
    payment_token: str = Field(alias='paymentToken')

    provider_i_d: typing.Optional[typing.Optional[str]] = Field(None, alias='providerID')

    profile_i_d: typing.Optional[typing.Optional[str]] = Field(None, alias='profileID')

    reference_i_d: typing.Optional[typing.Optional[str]] = Field(None, alias='referenceID')

    card_no: typing.Optional[typing.Optional[str]] = Field(None, alias='cardNo')

    expiry_month: typing.Optional[typing.Optional[str]] = Field(None, alias='expiryMonth')

    expiry_year: typing.Optional[typing.Optional[str]] = Field(None, alias='expiryYear')

    locale: typing.Optional[typing.Optional[str]] = Field(None, alias='locale')

    client_i_d: typing.Optional[str] = Field(None, alias='clientID')

    browser_details: typing.Optional[BrowserDetails] = Field(None, alias='browserDetails')
    class Config:
        arbitrary_types_allowed = True
