# coding: utf-8

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from 2c2p_python_sdk.pydantic.payment_option_details_info import PaymentOptionDetailsInfo
from 2c2p_python_sdk.pydantic.payment_option_details_payment_code import PaymentOptionDetailsPaymentCode
from 2c2p_python_sdk.pydantic.payment_option_details_payment_input import PaymentOptionDetailsPaymentInput
from 2c2p_python_sdk.pydantic.payment_option_details_payment_validation import PaymentOptionDetailsPaymentValidation

class PaymentOptionDetailsPayment(BaseModel):
    info: typing.Optional[PaymentOptionDetailsInfo] = Field(None, alias='info')

    code: typing.Optional[PaymentOptionDetailsPaymentCode] = Field(None, alias='code')

    input: typing.Optional[PaymentOptionDetailsPaymentInput] = Field(None, alias='input')

    validation: typing.Optional[PaymentOptionDetailsPaymentValidation] = Field(None, alias='validation')
    class Config:
        arbitrary_types_allowed = True
