# coding: utf-8

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from 2c2p_python_sdk.pydantic.merchant_details import MerchantDetails
from 2c2p_python_sdk.pydantic.payment_channel_category import PaymentChannelCategory
from 2c2p_python_sdk.pydantic.transaction_details import TransactionDetails
from 2c2p_python_sdk.pydantic.user_details import UserDetails

class PaymentOptionResponse(BaseModel):
    payment_token: typing.Optional[typing.Optional[str]] = Field(None, alias='paymentToken')

    merchant_details: typing.Optional[MerchantDetails] = Field(None, alias='merchantDetails')

    transaction_details: typing.Optional[TransactionDetails] = Field(None, alias='transactionDetails')

    channel_categories: typing.Optional[typing.Optional[typing.List[PaymentChannelCategory]]] = Field(None, alias='channelCategories')

    user_details: typing.Optional[UserDetails] = Field(None, alias='userDetails')

    resp_code: typing.Optional[typing.Optional[str]] = Field(None, alias='respCode')

    resp_desc: typing.Optional[typing.Optional[str]] = Field(None, alias='respDesc')
    class Config:
        arbitrary_types_allowed = True
