# coding: utf-8

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from 2c2p_python_sdk.pydantic.currency_fx_rate import CurrencyFxRate

class PaymentExchangeRateConverterResponse(BaseModel):
    fx_rates: typing.Optional[typing.Optional[typing.List[CurrencyFxRate]]] = Field(None, alias='fxRates')

    provider_code: typing.Optional[typing.Optional[str]] = Field(None, alias='providerCode')

    expire: typing.Optional[typing.Optional[int]] = Field(None, alias='expire')

    payment_token: typing.Optional[typing.Optional[str]] = Field(None, alias='paymentToken')

    resp_code: typing.Optional[typing.Optional[str]] = Field(None, alias='respCode')

    resp_desc: typing.Optional[typing.Optional[str]] = Field(None, alias='respDesc')
    class Config:
        arbitrary_types_allowed = True
