# coding: utf-8

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from 2c2p_python_sdk.pydantic.response_payment_channel import ResponsePaymentChannel

class PaymentChannelCategory(BaseModel):
    groups: typing.Optional[typing.Optional[typing.List[ResponsePaymentChannel]]] = Field(None, alias='groups')

    id: typing.Optional[typing.Optional[int]] = Field(None, alias='id')

    sequence_no: typing.Optional[int] = Field(None, alias='sequenceNo')

    name: typing.Optional[typing.Optional[str]] = Field(None, alias='name')

    code: typing.Optional[typing.Optional[str]] = Field(None, alias='code')

    icon_url: typing.Optional[typing.Optional[str]] = Field(None, alias='iconUrl')

    logo_url: typing.Optional[typing.Optional[str]] = Field(None, alias='logoUrl')

    default: typing.Optional[bool] = Field(None, alias='default')

    channel_code: typing.Optional[typing.Optional[str]] = Field(None, alias='channelCode')

    agent_channel_code: typing.Optional[typing.Optional[str]] = Field(None, alias='agentChannelCode')

    option_name: typing.Optional[typing.Optional[str]] = Field(None, alias='optionName')

    payment_code: typing.Optional[typing.Optional[str]] = Field(None, alias='paymentCode')

    qr_type: typing.Optional[typing.Optional[str]] = Field(None, alias='qrType')

    expiration_timer: typing.Optional[typing.Optional[str]] = Field(None, alias='expirationTimer')

    expiration_description: typing.Optional[typing.Optional[str]] = Field(None, alias='expirationDescription')

    expiration: typing.Optional[bool] = Field(None, alias='expiration')
    class Config:
        arbitrary_types_allowed = True
