# coding: utf-8

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class PaymentChannelPreference(BaseModel):
    sequence_no: typing.Optional[int] = Field(None, alias='sequenceNo')

    category_code: typing.Optional[typing.Optional[str]] = Field(None, alias='categoryCode')

    group_code: typing.Optional[typing.Optional[str]] = Field(None, alias='groupCode')

    name: typing.Optional[typing.Optional[str]] = Field(None, alias='name')

    channel_code: typing.Optional[typing.Optional[str]] = Field(None, alias='channelCode')

    agent_code: typing.Optional[typing.Optional[str]] = Field(None, alias='agentCode')

    agent_channel_code: typing.Optional[typing.Optional[str]] = Field(None, alias='agentChannelCode')

    icon_url: typing.Optional[typing.Optional[str]] = Field(None, alias='iconUrl')

    logo_url: typing.Optional[typing.Optional[str]] = Field(None, alias='logoUrl')
    class Config:
        arbitrary_types_allowed = True
