# coding: utf-8

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class Recurring(BaseModel):
    amount: typing.Optional[typing.Optional[str]] = Field(None, alias='amount')

    interval: typing.Optional[int] = Field(None, alias='interval')

    count: typing.Optional[int] = Field(None, alias='count')

    charge_next_date: typing.Optional[typing.Optional[str]] = Field(None, alias='chargeNextDate')

    charge_on_date: typing.Optional[typing.Optional[str]] = Field(None, alias='chargeOnDate')
    class Config:
        arbitrary_types_allowed = True
