# coding: utf-8

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from 2c2p_python_sdk.pydantic.payment_item import PaymentItem
from 2c2p_python_sdk.pydantic.recurring import Recurring

class TransactionDetails(BaseModel):
    description: typing.Optional[typing.Optional[str]] = Field(None, alias='description')

    amount: typing.Optional[typing.Optional[str]] = Field(None, alias='amount')

    currency_code: typing.Optional[typing.Optional[str]] = Field(None, alias='currencyCode')

    invoice_no: typing.Optional[typing.Optional[str]] = Field(None, alias='invoiceNo')

    recurring: typing.Optional[Recurring] = Field(None, alias='recurring')

    date_time: typing.Optional[typing.Optional[str]] = Field(None, alias='dateTime')

    payment_items: typing.Optional[typing.Optional[typing.List[PaymentItem]]] = Field(None, alias='paymentItems')

    show_fx_rate: typing.Optional[bool] = Field(None, alias='showFxRate')
    class Config:
        arbitrary_types_allowed = True
