# coding: utf-8

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

import unittest

import 2c2p_python_sdk
from 2c2p_python_sdk.model.payment_loyalty_point_info_request import PaymentLoyaltyPointInfoRequest
from 2c2p_python_sdk import configuration


class TestPaymentLoyaltyPointInfoRequest(unittest.TestCase):
    """PaymentLoyaltyPointInfoRequest unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
