# coding: utf-8

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

import unittest

import 2c2p_python_sdk
from 2c2p_python_sdk.model.payment_params_request_v43 import PaymentParamsRequestV43
from 2c2p_python_sdk import configuration


class TestPaymentParamsRequestV43(unittest.TestCase):
    """PaymentParamsRequestV43 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
