# coding: utf-8

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import 2c2p_python_sdk
from 2c2p_python_sdk.paths.payment_4_3_exchangerate import post
from 2c2p_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestPayment43Exchangerate(ApiTestMixin, unittest.TestCase):
    """
    Payment43Exchangerate unit test stubs
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 200








if __name__ == '__main__':
    unittest.main()
