# coding: utf-8

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

from 2c2p_python_sdk.paths.payment_4_3_paymenttoken.post import GenerateTokenRaw


class PaymentTokenApiRaw(
    GenerateTokenRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
