# coding: utf-8

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

from 2c2p_python_sdk.paths.payment_4_3_paymentinstruction.post import SubmitInstruction
from 2c2p_python_sdk.apis.tags.payment_instruction_api_raw import PaymentInstructionApiRaw


class PaymentInstructionApi(
    SubmitInstruction,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: PaymentInstructionApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = PaymentInstructionApiRaw(api_client)
