# coding: utf-8

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from 2c2p_python_sdk import schemas  # noqa: F401


class MerchantConfigurationNotification(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            facebook = schemas.BoolSchema
            whatsApp = schemas.BoolSchema
            line = schemas.BoolSchema
            __annotations__ = {
                "facebook": facebook,
                "whatsApp": whatsApp,
                "line": line,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["facebook"]) -> MetaOapg.properties.facebook: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["whatsApp"]) -> MetaOapg.properties.whatsApp: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["line"]) -> MetaOapg.properties.line: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["facebook", "whatsApp", "line", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["facebook"]) -> typing.Union[MetaOapg.properties.facebook, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["whatsApp"]) -> typing.Union[MetaOapg.properties.whatsApp, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["line"]) -> typing.Union[MetaOapg.properties.line, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["facebook", "whatsApp", "line", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        facebook: typing.Union[MetaOapg.properties.facebook, bool, schemas.Unset] = schemas.unset,
        whatsApp: typing.Union[MetaOapg.properties.whatsApp, bool, schemas.Unset] = schemas.unset,
        line: typing.Union[MetaOapg.properties.line, bool, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'MerchantConfigurationNotification':
        return super().__new__(
            cls,
            *args,
            facebook=facebook,
            whatsApp=whatsApp,
            line=line,
            _configuration=_configuration,
            **kwargs,
        )
