# coding: utf-8

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from 2c2p_python_sdk import schemas  # noqa: F401


class PaymentOptionDetailsInfoProvider(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            
            
            class id(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'id':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
        
            @staticmethod
            def channels() -> typing.Type['PaymentOptionDetailsInfoProviderChannels']:
                return PaymentOptionDetailsInfoProviderChannels
        
            @staticmethod
            def merchantDetails() -> typing.Type['PodInfoProviderMerchantDetails']:
                return PodInfoProviderMerchantDetails
        
            @staticmethod
            def transactionDetails() -> typing.Type['PodInfoProviderTransactionDetails']:
                return PodInfoProviderTransactionDetails
            
            
            class terms(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'terms':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            termsConsent = schemas.BoolSchema
            __annotations__ = {
                "id": id,
                "channels": channels,
                "merchantDetails": merchantDetails,
                "transactionDetails": transactionDetails,
                "terms": terms,
                "termsConsent": termsConsent,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["channels"]) -> 'PaymentOptionDetailsInfoProviderChannels': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["merchantDetails"]) -> 'PodInfoProviderMerchantDetails': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["transactionDetails"]) -> 'PodInfoProviderTransactionDetails': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["terms"]) -> MetaOapg.properties.terms: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["termsConsent"]) -> MetaOapg.properties.termsConsent: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["id", "channels", "merchantDetails", "transactionDetails", "terms", "termsConsent", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> typing.Union[MetaOapg.properties.id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["channels"]) -> typing.Union['PaymentOptionDetailsInfoProviderChannels', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["merchantDetails"]) -> typing.Union['PodInfoProviderMerchantDetails', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["transactionDetails"]) -> typing.Union['PodInfoProviderTransactionDetails', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["terms"]) -> typing.Union[MetaOapg.properties.terms, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["termsConsent"]) -> typing.Union[MetaOapg.properties.termsConsent, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["id", "channels", "merchantDetails", "transactionDetails", "terms", "termsConsent", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        id: typing.Union[MetaOapg.properties.id, None, str, schemas.Unset] = schemas.unset,
        channels: typing.Union['PaymentOptionDetailsInfoProviderChannels', schemas.Unset] = schemas.unset,
        merchantDetails: typing.Union['PodInfoProviderMerchantDetails', schemas.Unset] = schemas.unset,
        transactionDetails: typing.Union['PodInfoProviderTransactionDetails', schemas.Unset] = schemas.unset,
        terms: typing.Union[MetaOapg.properties.terms, None, str, schemas.Unset] = schemas.unset,
        termsConsent: typing.Union[MetaOapg.properties.termsConsent, bool, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PaymentOptionDetailsInfoProvider':
        return super().__new__(
            cls,
            *args,
            id=id,
            channels=channels,
            merchantDetails=merchantDetails,
            transactionDetails=transactionDetails,
            terms=terms,
            termsConsent=termsConsent,
            _configuration=_configuration,
            **kwargs,
        )

from 2c2p_python_sdk.model.payment_option_details_info_provider_channels import PaymentOptionDetailsInfoProviderChannels
from 2c2p_python_sdk.model.pod_info_provider_merchant_details import PodInfoProviderMerchantDetails
from 2c2p_python_sdk.model.pod_info_provider_transaction_details import PodInfoProviderTransactionDetails
