# coding: utf-8

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from 2c2p_python_sdk import schemas  # noqa: F401


class PaymentOptionDetailsValidation(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def cardNo() -> typing.Type['PaymentOptionDetailsValidationCard']:
                return PaymentOptionDetailsValidationCard
            
            
            class cardTypes(
                schemas.ListBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneTupleMixin
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['PaymentOptionDetailsValidationCardType']:
                        return PaymentOptionDetailsValidationCardType
            
            
                def __new__(
                    cls,
                    *args: typing.Union[list, tuple, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'cardTypes':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            __annotations__ = {
                "cardNo": cardNo,
                "cardTypes": cardTypes,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cardNo"]) -> 'PaymentOptionDetailsValidationCard': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cardTypes"]) -> MetaOapg.properties.cardTypes: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["cardNo", "cardTypes", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cardNo"]) -> typing.Union['PaymentOptionDetailsValidationCard', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cardTypes"]) -> typing.Union[MetaOapg.properties.cardTypes, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["cardNo", "cardTypes", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        cardNo: typing.Union['PaymentOptionDetailsValidationCard', schemas.Unset] = schemas.unset,
        cardTypes: typing.Union[MetaOapg.properties.cardTypes, list, tuple, None, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PaymentOptionDetailsValidation':
        return super().__new__(
            cls,
            *args,
            cardNo=cardNo,
            cardTypes=cardTypes,
            _configuration=_configuration,
            **kwargs,
        )

from 2c2p_python_sdk.model.payment_option_details_validation_card import PaymentOptionDetailsValidationCard
from 2c2p_python_sdk.model.payment_option_details_validation_card_type import PaymentOptionDetailsValidationCardType
