# coding: utf-8

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from 2c2p_python_sdk import schemas  # noqa: F401


class PaymentLoyaltyPointInfoRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "paymentToken",
        }
        
        class properties:
            paymentToken = schemas.StrSchema
            
            
            class providerID(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'providerID':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class profileID(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'profileID':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class referenceID(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'referenceID':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class cardNo(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'cardNo':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class expiryMonth(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'expiryMonth':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class expiryYear(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'expiryYear':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class locale(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'locale':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            clientID = schemas.UUIDSchema
        
            @staticmethod
            def browserDetails() -> typing.Type['BrowserDetails']:
                return BrowserDetails
            __annotations__ = {
                "paymentToken": paymentToken,
                "providerID": providerID,
                "profileID": profileID,
                "referenceID": referenceID,
                "cardNo": cardNo,
                "expiryMonth": expiryMonth,
                "expiryYear": expiryYear,
                "locale": locale,
                "clientID": clientID,
                "browserDetails": browserDetails,
            }
    
    paymentToken: MetaOapg.properties.paymentToken
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["paymentToken"]) -> MetaOapg.properties.paymentToken: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["providerID"]) -> MetaOapg.properties.providerID: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["profileID"]) -> MetaOapg.properties.profileID: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["referenceID"]) -> MetaOapg.properties.referenceID: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cardNo"]) -> MetaOapg.properties.cardNo: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["expiryMonth"]) -> MetaOapg.properties.expiryMonth: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["expiryYear"]) -> MetaOapg.properties.expiryYear: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["locale"]) -> MetaOapg.properties.locale: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["clientID"]) -> MetaOapg.properties.clientID: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["browserDetails"]) -> 'BrowserDetails': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["paymentToken", "providerID", "profileID", "referenceID", "cardNo", "expiryMonth", "expiryYear", "locale", "clientID", "browserDetails", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["paymentToken"]) -> MetaOapg.properties.paymentToken: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["providerID"]) -> typing.Union[MetaOapg.properties.providerID, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["profileID"]) -> typing.Union[MetaOapg.properties.profileID, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["referenceID"]) -> typing.Union[MetaOapg.properties.referenceID, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cardNo"]) -> typing.Union[MetaOapg.properties.cardNo, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["expiryMonth"]) -> typing.Union[MetaOapg.properties.expiryMonth, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["expiryYear"]) -> typing.Union[MetaOapg.properties.expiryYear, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["locale"]) -> typing.Union[MetaOapg.properties.locale, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["clientID"]) -> typing.Union[MetaOapg.properties.clientID, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["browserDetails"]) -> typing.Union['BrowserDetails', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["paymentToken", "providerID", "profileID", "referenceID", "cardNo", "expiryMonth", "expiryYear", "locale", "clientID", "browserDetails", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        paymentToken: typing.Union[MetaOapg.properties.paymentToken, str, ],
        providerID: typing.Union[MetaOapg.properties.providerID, None, str, schemas.Unset] = schemas.unset,
        profileID: typing.Union[MetaOapg.properties.profileID, None, str, schemas.Unset] = schemas.unset,
        referenceID: typing.Union[MetaOapg.properties.referenceID, None, str, schemas.Unset] = schemas.unset,
        cardNo: typing.Union[MetaOapg.properties.cardNo, None, str, schemas.Unset] = schemas.unset,
        expiryMonth: typing.Union[MetaOapg.properties.expiryMonth, None, str, schemas.Unset] = schemas.unset,
        expiryYear: typing.Union[MetaOapg.properties.expiryYear, None, str, schemas.Unset] = schemas.unset,
        locale: typing.Union[MetaOapg.properties.locale, None, str, schemas.Unset] = schemas.unset,
        clientID: typing.Union[MetaOapg.properties.clientID, str, uuid.UUID, schemas.Unset] = schemas.unset,
        browserDetails: typing.Union['BrowserDetails', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PaymentLoyaltyPointInfoRequest':
        return super().__new__(
            cls,
            *args,
            paymentToken=paymentToken,
            providerID=providerID,
            profileID=profileID,
            referenceID=referenceID,
            cardNo=cardNo,
            expiryMonth=expiryMonth,
            expiryYear=expiryYear,
            locale=locale,
            clientID=clientID,
            browserDetails=browserDetails,
            _configuration=_configuration,
            **kwargs,
        )

from 2c2p_python_sdk.model.browser_details import BrowserDetails
