# coding: utf-8

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from 2c2p_python_sdk import schemas  # noqa: F401


class PaymentUserPreference(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def preference() -> typing.Type['UserPreference']:
                return UserPreference
            
            
            class paymentChannels(
                schemas.ListBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneTupleMixin
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['PaymentChannelPreference']:
                        return PaymentChannelPreference
            
            
                def __new__(
                    cls,
                    *args: typing.Union[list, tuple, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'paymentChannels':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            __annotations__ = {
                "preference": preference,
                "paymentChannels": paymentChannels,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["preference"]) -> 'UserPreference': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["paymentChannels"]) -> MetaOapg.properties.paymentChannels: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["preference", "paymentChannels", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["preference"]) -> typing.Union['UserPreference', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["paymentChannels"]) -> typing.Union[MetaOapg.properties.paymentChannels, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["preference", "paymentChannels", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        preference: typing.Union['UserPreference', schemas.Unset] = schemas.unset,
        paymentChannels: typing.Union[MetaOapg.properties.paymentChannels, list, tuple, None, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PaymentUserPreference':
        return super().__new__(
            cls,
            *args,
            preference=preference,
            paymentChannels=paymentChannels,
            _configuration=_configuration,
            **kwargs,
        )

from 2c2p_python_sdk.model.payment_channel_preference import PaymentChannelPreference
from 2c2p_python_sdk.model.user_preference import UserPreference
