# coding: utf-8

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from 2c2p_python_sdk import schemas  # noqa: F401


class TransactionStatusAdditionalInfo(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def merchantDetails() -> typing.Type['TransactionStatusMerchant']:
                return TransactionStatusMerchant
        
            @staticmethod
            def transactionDetails() -> typing.Type['TransactionStatusInfo']:
                return TransactionStatusInfo
        
            @staticmethod
            def paymentResultDetails() -> typing.Type['TransactionStatusPayment']:
                return TransactionStatusPayment
            __annotations__ = {
                "merchantDetails": merchantDetails,
                "transactionDetails": transactionDetails,
                "paymentResultDetails": paymentResultDetails,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["merchantDetails"]) -> 'TransactionStatusMerchant': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["transactionDetails"]) -> 'TransactionStatusInfo': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["paymentResultDetails"]) -> 'TransactionStatusPayment': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["merchantDetails", "transactionDetails", "paymentResultDetails", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["merchantDetails"]) -> typing.Union['TransactionStatusMerchant', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["transactionDetails"]) -> typing.Union['TransactionStatusInfo', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["paymentResultDetails"]) -> typing.Union['TransactionStatusPayment', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["merchantDetails", "transactionDetails", "paymentResultDetails", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        merchantDetails: typing.Union['TransactionStatusMerchant', schemas.Unset] = schemas.unset,
        transactionDetails: typing.Union['TransactionStatusInfo', schemas.Unset] = schemas.unset,
        paymentResultDetails: typing.Union['TransactionStatusPayment', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'TransactionStatusAdditionalInfo':
        return super().__new__(
            cls,
            *args,
            merchantDetails=merchantDetails,
            transactionDetails=transactionDetails,
            paymentResultDetails=paymentResultDetails,
            _configuration=_configuration,
            **kwargs,
        )

from 2c2p_python_sdk.model.transaction_status_info import TransactionStatusInfo
from 2c2p_python_sdk.model.transaction_status_merchant import TransactionStatusMerchant
from 2c2p_python_sdk.model.transaction_status_payment import TransactionStatusPayment
