# coding: utf-8

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from 2c2p_python_sdk import schemas  # noqa: F401


class TransactionStatusPayment(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            
            
            class description(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'description':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class code(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'code':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            autoRedirect = schemas.BoolSchema
            redirectImmediately = schemas.BoolSchema
            autoRedirectionTimer = schemas.Int32Schema
            
            
            class frontendReturnUrl(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'frontendReturnUrl':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class frontendReturnData(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'frontendReturnData':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            __annotations__ = {
                "description": description,
                "code": code,
                "autoRedirect": autoRedirect,
                "redirectImmediately": redirectImmediately,
                "autoRedirectionTimer": autoRedirectionTimer,
                "frontendReturnUrl": frontendReturnUrl,
                "frontendReturnData": frontendReturnData,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["description"]) -> MetaOapg.properties.description: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["code"]) -> MetaOapg.properties.code: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["autoRedirect"]) -> MetaOapg.properties.autoRedirect: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["redirectImmediately"]) -> MetaOapg.properties.redirectImmediately: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["autoRedirectionTimer"]) -> MetaOapg.properties.autoRedirectionTimer: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["frontendReturnUrl"]) -> MetaOapg.properties.frontendReturnUrl: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["frontendReturnData"]) -> MetaOapg.properties.frontendReturnData: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["description", "code", "autoRedirect", "redirectImmediately", "autoRedirectionTimer", "frontendReturnUrl", "frontendReturnData", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["description"]) -> typing.Union[MetaOapg.properties.description, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["code"]) -> typing.Union[MetaOapg.properties.code, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["autoRedirect"]) -> typing.Union[MetaOapg.properties.autoRedirect, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["redirectImmediately"]) -> typing.Union[MetaOapg.properties.redirectImmediately, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["autoRedirectionTimer"]) -> typing.Union[MetaOapg.properties.autoRedirectionTimer, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["frontendReturnUrl"]) -> typing.Union[MetaOapg.properties.frontendReturnUrl, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["frontendReturnData"]) -> typing.Union[MetaOapg.properties.frontendReturnData, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["description", "code", "autoRedirect", "redirectImmediately", "autoRedirectionTimer", "frontendReturnUrl", "frontendReturnData", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        description: typing.Union[MetaOapg.properties.description, None, str, schemas.Unset] = schemas.unset,
        code: typing.Union[MetaOapg.properties.code, None, str, schemas.Unset] = schemas.unset,
        autoRedirect: typing.Union[MetaOapg.properties.autoRedirect, bool, schemas.Unset] = schemas.unset,
        redirectImmediately: typing.Union[MetaOapg.properties.redirectImmediately, bool, schemas.Unset] = schemas.unset,
        autoRedirectionTimer: typing.Union[MetaOapg.properties.autoRedirectionTimer, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        frontendReturnUrl: typing.Union[MetaOapg.properties.frontendReturnUrl, None, str, schemas.Unset] = schemas.unset,
        frontendReturnData: typing.Union[MetaOapg.properties.frontendReturnData, None, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'TransactionStatusPayment':
        return super().__new__(
            cls,
            *args,
            description=description,
            code=code,
            autoRedirect=autoRedirect,
            redirectImmediately=redirectImmediately,
            autoRedirectionTimer=autoRedirectionTimer,
            frontendReturnUrl=frontendReturnUrl,
            frontendReturnData=frontendReturnData,
            _configuration=_configuration,
            **kwargs,
        )
