# coding: utf-8

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredAddress(TypedDict):
    pass

class OptionalAddress(TypedDict, total=False):
    address1: typing.Optional[str]

    address2: typing.Optional[str]

    address3: typing.Optional[str]

    postalCode: typing.Optional[str]

    city: typing.Optional[str]

    state: typing.Optional[str]

    countryCode: typing.Optional[str]

class Address(RequiredAddress, OptionalAddress):
    pass
