# coding: utf-8

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredCreditCardTokenV43(TypedDict):
    pass

class OptionalCreditCardTokenV43(TypedDict, total=False):
    token: typing.Optional[str]

    accountNo: typing.Optional[str]

    name: typing.Optional[str]

    email: typing.Optional[str]

    expiry: typing.Optional[str]

    channelCode: typing.Optional[str]

    subChannelCode: typing.Optional[str]

    cardBrand: typing.Optional[str]

    status: typing.Optional[str]

    iconUrl: typing.Optional[str]

    logoUrl: typing.Optional[str]

class CreditCardTokenV43(RequiredCreditCardTokenV43, OptionalCreditCardTokenV43):
    pass
