# coding: utf-8

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredCurrencyAPMMCCFxRate(TypedDict):
    pass

class OptionalCurrencyAPMMCCFxRate(TypedDict, total=False):
    expire: int

    sequenceNo: int

    id: typing.Optional[str]

    fx: typing.Union[int, float]

    currencyCode: typing.Optional[str]

class CurrencyAPMMCCFxRate(RequiredCurrencyAPMMCCFxRate, OptionalCurrencyAPMMCCFxRate):
    pass
