# coding: utf-8

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredIppPlan(TypedDict):
    pass

class OptionalIppPlan(TypedDict, total=False):
    sequenceNo: int

    period: int

    interestType: typing.Optional[str]

    interestRate: typing.Union[int, float]

    monthlyAmount: typing.Union[int, float]

    monthlyInterest: typing.Union[int, float]

    currencyCode: typing.Optional[str]

    label: typing.Optional[str]

    terms: typing.Optional[str]

    payLaterPeriod: typing.Optional[int]

class IppPlan(RequiredIppPlan, OptionalIppPlan):
    pass
