# coding: utf-8

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from 2c2p_python_sdk.type.loyalty_rewards import LoyaltyRewards

class RequiredLoyaltyDetails(TypedDict):
    pass

class OptionalLoyaltyDetails(TypedDict, total=False):
    providerID: typing.Optional[str]

    accountNo: typing.Optional[str]

    accountAuthData: typing.Optional[str]

    queryReferenceSpecified: bool

    externalMerchantId: typing.Optional[str]

    redeemAmount: typing.Union[int, float]

    rewards: typing.Optional[typing.List[LoyaltyRewards]]

class LoyaltyDetails(RequiredLoyaltyDetails, OptionalLoyaltyDetails):
    pass
