# coding: utf-8

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from 2c2p_python_sdk.type.merchant_configuration_notification import MerchantConfigurationNotification
from 2c2p_python_sdk.type.merchant_configuration_payment import MerchantConfigurationPayment

class RequiredMerchantConfiguration(TypedDict):
    pass

class OptionalMerchantConfiguration(TypedDict, total=False):
    payment: MerchantConfigurationPayment

    notification: MerchantConfigurationNotification

class MerchantConfiguration(RequiredMerchantConfiguration, OptionalMerchantConfiguration):
    pass
