# coding: utf-8

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredMerchantValidationApplePayResponse(TypedDict):
    pass

class OptionalMerchantValidationApplePayResponse(TypedDict, total=False):
    epochTimestamp: int

    expiresAt: int

    merchantSessionIdentifier: typing.Optional[str]

    nonce: typing.Optional[str]

    merchantIdentifier: typing.Optional[str]

    domainName: typing.Optional[str]

    displayName: typing.Optional[str]

    signature: typing.Optional[str]

    operationalAnalyticsIdentifier: typing.Optional[str]

    retries: int

    pspId: typing.Optional[str]

    respCode: typing.Optional[str]

    respDesc: typing.Optional[str]

class MerchantValidationApplePayResponse(RequiredMerchantValidationApplePayResponse, OptionalMerchantValidationApplePayResponse):
    pass
