# coding: utf-8

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from 2c2p_python_sdk.type.browser_details import BrowserDetails

class RequiredPaymentExchangeRateConverterRequest(TypedDict):
    paymentToken: str

class OptionalPaymentExchangeRateConverterRequest(TypedDict, total=False):
    bin: typing.Optional[str]

    locale: typing.Optional[str]

    clientID: str

    browserDetails: BrowserDetails

class PaymentExchangeRateConverterRequest(RequiredPaymentExchangeRateConverterRequest, OptionalPaymentExchangeRateConverterRequest):
    pass
