# coding: utf-8

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredPaymentLoyaltyReward(TypedDict):
    pass

class OptionalPaymentLoyaltyReward(TypedDict, total=False):
    sequenceNo: int

    id: typing.Optional[str]

    currencyCode: typing.Optional[str]

    totalPoints: typing.Union[int, float]

    label: typing.Optional[str]

    point: typing.Union[int, float]

    forceToSelectReward: bool

    name: typing.Optional[str]

    type: typing.Optional[str]

    amount: typing.Union[int, float]

    quantity: typing.Union[int, float]

    price: typing.Union[int, float]

class PaymentLoyaltyReward(RequiredPaymentLoyaltyReward, OptionalPaymentLoyaltyReward):
    pass
