# coding: utf-8

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from 2c2p_python_sdk.type.payment_option_details_validation_card_type_prefixes import PaymentOptionDetailsValidationCardTypePrefixes

class RequiredPaymentOptionDetailsValidationCardType(TypedDict):
    pass

class OptionalPaymentOptionDetailsValidationCardType(TypedDict, total=False):
    sequenceNo: int

    name: typing.Optional[str]

    prefixes: PaymentOptionDetailsValidationCardTypePrefixes

    regex: typing.Optional[str]

    iconUrl: typing.Optional[str]

class PaymentOptionDetailsValidationCardType(RequiredPaymentOptionDetailsValidationCardType, OptionalPaymentOptionDetailsValidationCardType):
    pass
