# coding: utf-8

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredPaymentChannelPreference(TypedDict):
    pass

class OptionalPaymentChannelPreference(TypedDict, total=False):
    sequenceNo: int

    categoryCode: typing.Optional[str]

    groupCode: typing.Optional[str]

    name: typing.Optional[str]

    channelCode: typing.Optional[str]

    agentCode: typing.Optional[str]

    agentChannelCode: typing.Optional[str]

    iconUrl: typing.Optional[str]

    logoUrl: typing.Optional[str]

class PaymentChannelPreference(RequiredPaymentChannelPreference, OptionalPaymentChannelPreference):
    pass
