# coding: utf-8

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from 2c2p_python_sdk.type.browser_details import BrowserDetails
from 2c2p_python_sdk.type.payment_params_request_v43 import PaymentParamsRequestV43

class RequiredPaymentRequestV43(TypedDict):
    paymentToken: str

class OptionalPaymentRequestV43(TypedDict, total=False):
    payment: PaymentParamsRequestV43

    responseReturnUrl: typing.Optional[str]

    clientIP: typing.Optional[str]

    locale: typing.Optional[str]

    clientID: str

    browserDetails: BrowserDetails

class PaymentRequestV43(RequiredPaymentRequestV43, OptionalPaymentRequestV43):
    pass
