# coding: utf-8

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from 2c2p_python_sdk.type.payment_channel_preference import PaymentChannelPreference
from 2c2p_python_sdk.type.user_preference import UserPreference

class RequiredPaymentUserPreference(TypedDict):
    pass

class OptionalPaymentUserPreference(TypedDict, total=False):
    preference: UserPreference

    paymentChannels: typing.Optional[typing.List[PaymentChannelPreference]]

class PaymentUserPreference(RequiredPaymentUserPreference, OptionalPaymentUserPreference):
    pass
