# coding: utf-8

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from 2c2p_python_sdk.type.payment_option_details_info_provider_channels import PaymentOptionDetailsInfoProviderChannels
from 2c2p_python_sdk.type.pod_info_provider_merchant_details import PodInfoProviderMerchantDetails
from 2c2p_python_sdk.type.pod_info_provider_transaction_details import PodInfoProviderTransactionDetails

class RequiredPaymentOptionDetailsInfoProvider(TypedDict):
    pass

class OptionalPaymentOptionDetailsInfoProvider(TypedDict, total=False):
    id: typing.Optional[str]

    channels: PaymentOptionDetailsInfoProviderChannels

    merchantDetails: PodInfoProviderMerchantDetails

    transactionDetails: PodInfoProviderTransactionDetails

    terms: typing.Optional[str]

    termsConsent: bool

class PaymentOptionDetailsInfoProvider(RequiredPaymentOptionDetailsInfoProvider, OptionalPaymentOptionDetailsInfoProvider):
    pass
