# coding: utf-8

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from 2c2p_python_sdk.type.browser_details import BrowserDetails

class RequiredPaymentLoyaltyPointInfoRequest(TypedDict):
    paymentToken: str

class OptionalPaymentLoyaltyPointInfoRequest(TypedDict, total=False):
    providerID: typing.Optional[str]

    profileID: typing.Optional[str]

    referenceID: typing.Optional[str]

    cardNo: typing.Optional[str]

    expiryMonth: typing.Optional[str]

    expiryYear: typing.Optional[str]

    locale: typing.Optional[str]

    clientID: str

    browserDetails: BrowserDetails

class PaymentLoyaltyPointInfoRequest(RequiredPaymentLoyaltyPointInfoRequest, OptionalPaymentLoyaltyPointInfoRequest):
    pass
