# coding: utf-8

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from 2c2p_python_sdk.type.payment_option_details_payment_code import PaymentOptionDetailsPaymentCode
from 2c2p_python_sdk.type.payment_params_data_request_v43 import PaymentParamsDataRequestV43

class RequiredPaymentParamsRequestV43(TypedDict):
    pass

class OptionalPaymentParamsRequestV43(TypedDict, total=False):
    data: PaymentParamsDataRequestV43

    code: PaymentOptionDetailsPaymentCode

class PaymentParamsRequestV43(RequiredPaymentParamsRequestV43, OptionalPaymentParamsRequestV43):
    pass
