# coding: utf-8

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredPodInfoProviderTransactionDetails(TypedDict):
    pass

class OptionalPodInfoProviderTransactionDetails(TypedDict, total=False):
    description: typing.Optional[str]

    amount: typing.Union[int, float]

    currencyCode: typing.Optional[str]

    invoiceNo: typing.Optional[str]

class PodInfoProviderTransactionDetails(RequiredPodInfoProviderTransactionDetails, OptionalPodInfoProviderTransactionDetails):
    pass
