# coding: utf-8

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredResponsePaymentChannel(TypedDict):
    pass

class OptionalResponsePaymentChannel(TypedDict, total=False):
    id: typing.Optional[int]

    sequenceNo: int

    name: typing.Optional[str]

    code: typing.Optional[str]

    iconUrl: typing.Optional[str]

    logoUrl: typing.Optional[str]

    default: bool

    channelCode: typing.Optional[str]

    agentChannelCode: typing.Optional[str]

    optionName: typing.Optional[str]

    paymentCode: typing.Optional[str]

    qrType: typing.Optional[str]

    expirationTimer: typing.Optional[str]

    expirationDescription: typing.Optional[str]

    expiration: bool

class ResponsePaymentChannel(RequiredResponsePaymentChannel, OptionalResponsePaymentChannel):
    pass
