# coding: utf-8

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from 2c2p_python_sdk.type.transaction_status_rewards import TransactionStatusRewards

class RequiredTransactionStatusLoyaltyInfo(TypedDict):
    pass

class OptionalTransactionStatusLoyaltyInfo(TypedDict, total=False):
    paymentScheme: typing.Optional[str]

    redeemAmount: typing.Union[int, float]

    rewards: typing.Optional[typing.List[TransactionStatusRewards]]

class TransactionStatusLoyaltyInfo(RequiredTransactionStatusLoyaltyInfo, OptionalTransactionStatusLoyaltyInfo):
    pass
