# coding: utf-8

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredUserPreference(TypedDict):
    pass

class OptionalUserPreference(TypedDict, total=False):
    name: typing.Optional[str]

    email: typing.Optional[str]

    mobileNo: typing.Optional[str]

    mobileNoPrefix: typing.Optional[str]

    locale: typing.Optional[str]

    currencyCode: typing.Optional[str]

    countryCode: typing.Optional[str]

class UserPreference(RequiredUserPreference, OptionalUserPreference):
    pass
