# coding: utf-8

# flake8: noqa

"""
    PGW Payment API 4.3

    Rest API for PGW payment purpose - LATEST

    The version of the OpenAPI document: 4.3
    Generated by: https://konfigthis.com
"""

__version__ = "4.3"

# import ApiClient
from 2c2p_python_sdk.api_client import ApiClient

# import Configuration
from 2c2p_python_sdk.configuration import Configuration

# import exceptions
from 2c2p_python_sdk.exceptions import OpenApiException
from 2c2p_python_sdk.exceptions import ApiAttributeError
from 2c2p_python_sdk.exceptions import ApiTypeError
from 2c2p_python_sdk.exceptions import ApiValueError
from 2c2p_python_sdk.exceptions import ApiKeyError
from 2c2p_python_sdk.exceptions import ApiException

from 2c2p_python_sdk.client import TwoCTwoP
